### ISSUE TITLE
Error while extracting the downloaded file(s)

### ISSUE THREAD

**Issue by BJTMastermind** [ChristopherHX/mcpelauncher-ui-manifest#15] opened 2020-11-26 05:46 UTC
I was trying to download MCPE version 0.8.1 (x86) from the launcher it started to download then about half way it gave an error that says:
```
Error while extracting the downloaded file(s), please report this error:
unsupported, versionname of the apk isn't empty, but property versionName is set
```
I do own Minecraft for Android so im not sure why it failed to download it.

**Comment by VoxelBill** [comment] 2020-11-26 06:00
EDIT: After trying to load 0.8.1 and go back to the latest version it wont load when it did before.

**Comment by ChristopherHX** [comment] 2020-11-26 10:02
Please provide the content of this file `~/.local/share/mcpelauncher/versions/versions.ini` and the result of `tree -L 4 ~/.local/share/mcpelauncher/versions/` (Directory structure)
It may contain corrupted or out of sync entries.
Maybe in such case the launcher should try to repair itself or ignore this violation.

Neverthingless < 1.1 won't work
0.12-1.0 only works on previous versions of the Launcher
I only added 0.8-0.11 to preserve the versionscodes

**Comment by ChristopherHX** [comment] 2020-11-26 10:10
I can reproduce this with 1.14.60.5 x86_64 then also downloading 1.14.60.5 x86 finally selecting Google Play latest then it doesn't work.
I will silence this error, it would work otherwise
```
Error while extracting the downloaded file(s), please report this error:
unsupported, versionname of the apk isn't empty, but property versionName is set
```

Weird that latest version then stops working, but changing the version to an explicit version fixed it again.

**Comment by ChristopherHX** [comment] 2020-11-26 10:18
To work around your second bug with the latest version
- explicitly select a x86_64 version
then it should work again.

Need to be fixed, thanks for your report.

**Comment by VoxelBill** [comment] 2020-11-26 16:52
version.ini contents 
```
[0.8.1]
codes\1\arch=x86
codes\1\code=700801011
codes\size=1
versionCode=700801011
versionName=0.8.1

[1.16.101.01]
codes\1\arch=x86_64
codes\1\code=981610101
codes\size=1
versionCode=981610101
versionName=1.16.101.01
```
output.txt has the result of the tree command
[output.txt](https://github.com/ChristopherHX/mcpelauncher-ui-manifest/files/5604238/output.txt)

**Comment by ChristopherHX** [comment] 2020-11-28 16:23
Your files look good, nothing wrong there.
I published an update for linux/AppImage to address the two bugs.
Could you please test again to verify if it is fixed or still broken.
_If it's fixed please close this issue_

**Comment by VoxelBill** [comment] 2020-12-01 21:28
I got the notification in the launcher for the update but when i click it nothing is downloading and in the terminal its spamming
```
qrc:/qml/main.qml:197: ReferenceError: downloadProgress is not defined
```
so im unable to test right now if your fix works.

**Comment by ChristopherHX** [comment] 2020-12-01 21:30
Just wait, it will install the update just no progressbar
Von: BJTMastermind
Gesendet: Dienstag, 1. Dezember 2020 22:29
An: ChristopherHX/mcpelauncher-ui-manifest
Cc: ChristopherHX; Comment
Betreff: Re: [ChristopherHX/mcpelauncher-ui-manifest] Error while extractingthe downloaded file(s) (#15)

I got the notification in the launcher for the update but when i click it nothing is downloading and in the terminal its spamming
qrc:/qml/main.qml:197: ReferenceError: downloadProgress is not defined
so im unable to test right now if your fix works.

**Comment by VoxelBill** [comment] 2020-12-01 21:38
The issue is fixed

**Closed as completed by VoxelBill** 2020-12-01 21:38 UTC
